Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
Traceback (most recent call last):
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 421, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./probing.py", line 32, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 423, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '../X/X9/X_GTT_Sent_Epoch5.npy' as a pickle
